package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"
	req "github.com/imroc/req/v3"
	"gitlab.informatik.hs-augsburg.de/flomon/waaf/services/api-gateway/graph/model"

	. "gitlab.informatik.hs-augsburg.de/flomon/waaf/services/api-gateway/graph/utils"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.UserRegistrationData) (*model.Token, error) {
	resp, err := req.R().
		SetBody(input).
		SetContentType("application/json").
		Post(fmt.Sprintf("%s/register", AuthenticationServiceUrl))

	if err != nil {
		return nil, err
	}
	if resp.IsError() {
		return nil, fmt.Errorf("%s", resp.String())
	}
	if resp.IsSuccess() {
		return &model.Token{Token: resp.String()}, nil
	}
	return nil, fmt.Errorf("got unexpected response, raw dump:\n%s", resp.Dump())
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, input model.UserLoginData) (*model.Token, error) {
	resp, err := req.R().
		SetBody(input).
		SetContentType("application/json").
		Post(fmt.Sprintf("%s/login", AuthenticationServiceUrl))

	if err != nil {
		return nil, err
	}
	if resp.IsError() {
		return nil, fmt.Errorf("%s", resp.String())
	}
	if resp.IsSuccess() {
		return &model.Token{Token: resp.String()}, nil
	}
	return nil, fmt.Errorf("got unexpected response, raw dump:\n%s", resp.Dump())
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
