version: "3.9"
services:
  waaf_stack:
    image: nginx
    container_name: waaf_function_group_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./lib:/etc/nginx/njs
    ports:
      - "8888:80"
    environment:
     NGINX_PORT: 80
     GROUP_ID: some_random_uuid
     NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx