[package]
name = "sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "sum"
path = "src/main.rs"

[dependencies]
waaf = { path = "../../" }
httpcodec = "0.2.3"
bytecodec = "0.4.15"