apiVersion: apps/v1
kind: Deployment
metadata:
  name: waaf-services-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waaf-services-deployer
  template:
    metadata:
      labels:
        app: waaf-services-deployer
    spec:
      containers:
        - name: waaf-services-deployer
          image: localhost:5001/waaf/services/deployer
          ports:
            - containerPort: 10003
---
apiVersion: v1
kind: Service
metadata:
  name: waaf-services-deployer-service
spec:
  ports:
    - port: 10003
  selector:
    app: waaf-services-deployer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: waaf-services-deployer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /deployer
            backend:
              service:
                name: waaf-services-deployer-service
                port:
                  number: 10003