apiVersion: apps/v1
kind: Deployment
metadata:
  name: waaf-services-api
  namespace: waaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waaf-services-api
  template:
    metadata:
      labels:
        app: waaf-services-api
    spec:
      containers:
        - name: waaf-services-api
          image: localhost:5001/waaf/services/api
          imagePullPolicy: Always
          env:
            - name: FUNCTIONGROUP_URL
              value: http://waaf-services-fn-group-service.waaf.svc.cluster.local:8080
            - name: AUTHENTICATION_URL
              value: http://waaf-services-auth-service.waaf.svc.cluster.local:8080
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: waaf
  name: waaf-services-api-service
spec:
  ports:
    - port: 8080
  selector:
    app: waaf-services-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: waaf
  name: waaf-services-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /graphql(/|$)(.*)
            backend:
              service:
                name: waaf-services-api-service
                port:
                  number: 8080