apiVersion: v1
kind: Pod
metadata:
  name: waaf-authentication
  namespace: default
  annotations:
    module.wasm.image/variant: compat-smart
spec:
  hostNetwork: true
  containers:
    - name: waaf-authentication
      image: core.harbor.domain/library/waaf-authentication
      command: [ "/test-may-minihttp.wasm" ]
      ports:
        - containerPort: 1234
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 1234
        initialDelaySeconds: 3
        periodSeconds: 30
  imagePullSecrets:
    - name: regcred

